[ENG-2946] Fix a11y problems on discover page
CenterForOpenScience/ember-osf-preprints pull request #728
Opened 2021-07-20 19:15 UTC by brianjgeiger

## Purpose
Fixes a11y issues on the discover page.

## Summary of Changes/Side Effects
1. Add `lang=eng-us` to HTML tag
2. Add `role=option` to options inside carousel
3. Add aria-label to disclosure triangles for subjects
4. Update version of ember-osf to fix aria-label for search box
5. Add yalc-specific gitignores

## Testing Notes
This will need to be run through the selenium AXE tests again to see if these fixes did what they were supposed to. Nothing should be broken as far as functionality goes.

## Ticket

https://openscience.atlassian.net/browse/ENG-2946

## Notes for Reviewer

# Reviewer Checklist

- [ ] meets requirements
- [ ] easy to understand
- [ ] DRY
- [ ] testable and includes test(s)
- [ ] changes described in `CHANGELOG.md`

2021-07-29 20:25 UTC, fabmiz approved these changes

2021-08-04 18:08 UTC, futa-ikeda requested changes
One minor fix to get the role=button and aria-label picked up properly

2021-08-04 18:19 UTC, brianjgeiger commented on app/templates/components/search-facet-taxonomy.hbs
> +                    role="button"
Fixed

2021-08-04 18:21 UTC, futa-ikeda submitted a review, later dismissed
🚀

2021-08-04 18:37 UTC, fabmiz reviewed
@brianjgeiger, we need to re-yarn because of the `ember-osf` dependency update

2021-08-04 19:49 UTC, brianjgeiger commented
@fabmiz Done, and tests are passing.

2021-08-04 20:56 UTC, merged