[ENG-4460] Toggle assertions based on preprint-provider flag
CenterForOpenScience/ember-osf-preprints pull request #756
Opened 2023-09-07 22:34 UTC by futa-ikeda

## Purpose
- Show/Hide Assertions/COI panels in submit page based on a preprint-provider flag (`assertions_enabled`)

## Summary of Changes/Side Effects
- Add `assertionsEnabled` flag to `submit` page controller
  - controls which panels are visible (hide COI and Assertions based on this flag)
  - controls which validations occur
  - controls which validation errors are shown

## Testing Notes
- Will need to toggle the `assertions_enabled` flag on the preprint_provider page in the admin app

## Ticket

https://openscience.atlassian.net/browse/ENG-4460

## Notes for Reviewer

# Reviewer Checklist

- [ ] meets requirements
- [ ] easy to understand
- [ ] DRY
- [ ] testable and includes test(s)
- [ ] changes described in `CHANGELOG.md`

2023-09-08 17:46 UTC, futa-ikeda commented on tests/unit/controllers/submit-test.js
A *real* fix would be to make two separate test cases for the `PreprintProver.assertionsEnabled` flag turned on and off, but I can't seem to get the changes in my preprint-provider factory in eosf to show up here :/

2023-09-08 17:50 UTC, futa-ikeda commented on package.json
> +    "@centerforopenscience/ember-osf": "https://github.com/CenterForOpenScience/ember-osf.git#feature\/custom-preprint-citation",
Note to self: make sure this is updated on release

2023-09-08 17:58 UTC, brianjgeiger requested changes
Approved except for the pointing to a feature branch of ember-osf and mayyybe updating the test if you've figured out your problems there.

2023-09-08 17:58 UTC, brianjgeiger commented on tests/unit/controllers/submit-test.js
Is this still true that you can't get the changes to show?

2023-09-08 21:00 UTC, futa-ikeda commented on tests/unit/controllers/submit-test.js
I'm not getting the changes to show, but I can just hack it with something like `ctrl.set('selectedProvider', { assertionsEnabled: true });` so I'm adding a couple tests that do that.

2023-09-12 14:35 UTC, brianjgeiger approved these changes

2023-09-12 14:52 UTC, merged